main: io.papermc.fullbrightextended.FullbrightExtended
name: FullbrightExtended
version: '1.3'
commands:
  fullbright:
    description: Activates/deactivates fullbright
    usage: /fullbright [playerName] [on|off]
    aliases: [fb, fubr, light]
    permission: FullbrightExtended.command.fullbrightextended
  fblanguage:
    description: Changes the language of the plugin
    usage: /fblanguage [language]
    permission: FullbrightExtended.language.language
permissions:
  FullbrightExtended.command.fullbrightextended:
    description: Allows use of the fullbright command
    default: true
  FullbrightExtended.command.fullbrightextendedarguments:
    description: Allows the use of the paremeters on the fullbright command
    default: op
  FullbrightExtended.language.language:
    description: Allows the use of the fblanguage command
    default: op
